name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: make install
      - name: Format
        run: make format
      - name: Train
        run: make train
      - name: Evaluation
        run: make eval
