name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
      - name: Install Packages
        run: make install
      - name: Format
        run: make format
      - name: Train
        run: make train
      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval
      - name: Update Branch
        run: |
          git config --global user.name abid
          git config --global user.email 1abid@duck.com
          git remote add origin https://kingabzp:${{ secrets.GITHUB_TOKEN }}github.com/kingabzpro/CICD-for-Machine-Learning.git
          git commit -am "Update with new results"
          git push -u origin update