name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v2
      - env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Can use the default token for most functions
      - name: Install Packages
        run: make install
      - name: Format
        run: make format
      - name: Train
        run: make train
      - name: Evaluation
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: make eval
